# Generated by Django 5.0.6 on 2024-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_category_background_color_alter_postlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Regular'), (2, 'Assignment')],
                                                   default=1),
        ),
    ]
