# Generated by Django 5.0.6 on 2024-09-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_type_alter_postlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_latex',
            field=models.BooleanField(default=False),
        ),
    ]
